// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test
int test();
RcppExport SEXP _wishartinference_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test());
    return rcpp_result_gen;
END_RCPP
}
// rwishart
arma::cube rwishart(int n, int p, double nu, const arma::mat& Sigma);
RcppExport SEXP _wishartinference_rwishart(SEXP nSEXP, SEXP pSEXP, SEXP nuSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(rwishart(n, p, nu, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// lgammap_export
double lgammap_export(double a, int p);
RcppExport SEXP _wishartinference_lgammap_export(SEXP aSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(lgammap_export(a, p));
    return rcpp_result_gen;
END_RCPP
}
// ldet
double ldet(const arma::mat& X);
RcppExport SEXP _wishartinference_ldet(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(ldet(X));
    return rcpp_result_gen;
END_RCPP
}
// wishart_stats
Rcpp::List wishart_stats(const arma::cube& X);
RcppExport SEXP _wishartinference_wishart_stats(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(wishart_stats(X));
    return rcpp_result_gen;
END_RCPP
}
// lfafun_improper
double lfafun_improper(double a, int n, int p, const arma::mat& xbar, double ldetxbarg);
RcppExport SEXP _wishartinference_lfafun_improper(SEXP aSEXP, SEXP nSEXP, SEXP pSEXP, SEXP xbarSEXP, SEXP ldetxbargSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xbar(xbarSEXP);
    Rcpp::traits::input_parameter< double >::type ldetxbarg(ldetxbargSEXP);
    rcpp_result_gen = Rcpp::wrap(lfafun_improper(a, n, p, xbar, ldetxbarg));
    return rcpp_result_gen;
END_RCPP
}
// lfafun_proper
double lfafun_proper(double a, int n, int p, double ldet_muhat, double ldetxbarg, double ldet_mu0, double beta, double eta, double kappa);
RcppExport SEXP _wishartinference_lfafun_proper(SEXP aSEXP, SEXP nSEXP, SEXP pSEXP, SEXP ldet_muhatSEXP, SEXP ldetxbargSEXP, SEXP ldet_mu0SEXP, SEXP betaSEXP, SEXP etaSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type ldet_muhat(ldet_muhatSEXP);
    Rcpp::traits::input_parameter< double >::type ldetxbarg(ldetxbargSEXP);
    Rcpp::traits::input_parameter< double >::type ldet_mu0(ldet_mu0SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(lfafun_proper(a, n, p, ldet_muhat, ldetxbarg, ldet_mu0, beta, eta, kappa));
    return rcpp_result_gen;
END_RCPP
}
// mode_alphaEM
Rcpp::NumericVector mode_alphaEM(int n, int p, const arma::mat& xbar, double ldetxbarg, Rcpp::Nullable<arma::mat> mu0_, double beta, double eta, double kappa, double tol, bool prnt, int max_em_iter, int max_nr_iter);
RcppExport SEXP _wishartinference_mode_alphaEM(SEXP nSEXP, SEXP pSEXP, SEXP xbarSEXP, SEXP ldetxbargSEXP, SEXP mu0_SEXP, SEXP betaSEXP, SEXP etaSEXP, SEXP kappaSEXP, SEXP tolSEXP, SEXP prntSEXP, SEXP max_em_iterSEXP, SEXP max_nr_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xbar(xbarSEXP);
    Rcpp::traits::input_parameter< double >::type ldetxbarg(ldetxbargSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type mu0_(mu0_SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type prnt(prntSEXP);
    Rcpp::traits::input_parameter< int >::type max_em_iter(max_em_iterSEXP);
    Rcpp::traits::input_parameter< int >::type max_nr_iter(max_nr_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(mode_alphaEM(n, p, xbar, ldetxbarg, mu0_, beta, eta, kappa, tol, prnt, max_em_iter, max_nr_iter));
    return rcpp_result_gen;
END_RCPP
}
// rejection_sampler
Rcpp::List rejection_sampler(double ahat, double mxlfa, double lambda, double nu_star, int p, int n, const arma::mat& xbar, double ldetxbarg, Rcpp::Nullable<arma::mat> mu0_, double beta, double eta, double kappa, int nsamp);
RcppExport SEXP _wishartinference_rejection_sampler(SEXP ahatSEXP, SEXP mxlfaSEXP, SEXP lambdaSEXP, SEXP nu_starSEXP, SEXP pSEXP, SEXP nSEXP, SEXP xbarSEXP, SEXP ldetxbargSEXP, SEXP mu0_SEXP, SEXP betaSEXP, SEXP etaSEXP, SEXP kappaSEXP, SEXP nsampSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type ahat(ahatSEXP);
    Rcpp::traits::input_parameter< double >::type mxlfa(mxlfaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type nu_star(nu_starSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type xbar(xbarSEXP);
    Rcpp::traits::input_parameter< double >::type ldetxbarg(ldetxbargSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type mu0_(mu0_SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    rcpp_result_gen = Rcpp::wrap(rejection_sampler(ahat, mxlfa, lambda, nu_star, p, n, xbar, ldetxbarg, mu0_, beta, eta, kappa, nsamp));
    return rcpp_result_gen;
END_RCPP
}
// wishart_inference
Rcpp::List wishart_inference(arma::cube& X, Rcpp::Nullable<arma::mat> mu0_, double beta, double eta, double kappa, int nsamp, double tol, bool prnt, int max_em_iter, int max_nr_iter);
RcppExport SEXP _wishartinference_wishart_inference(SEXP XSEXP, SEXP mu0_SEXP, SEXP betaSEXP, SEXP etaSEXP, SEXP kappaSEXP, SEXP nsampSEXP, SEXP tolSEXP, SEXP prntSEXP, SEXP max_em_iterSEXP, SEXP max_nr_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::mat> >::type mu0_(mu0_SEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type prnt(prntSEXP);
    Rcpp::traits::input_parameter< int >::type max_em_iter(max_em_iterSEXP);
    Rcpp::traits::input_parameter< int >::type max_nr_iter(max_nr_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(wishart_inference(X, mu0_, beta, eta, kappa, nsamp, tol, prnt, max_em_iter, max_nr_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wishartinference_test", (DL_FUNC) &_wishartinference_test, 0},
    {"_wishartinference_rwishart", (DL_FUNC) &_wishartinference_rwishart, 4},
    {"_wishartinference_lgammap_export", (DL_FUNC) &_wishartinference_lgammap_export, 2},
    {"_wishartinference_ldet", (DL_FUNC) &_wishartinference_ldet, 1},
    {"_wishartinference_wishart_stats", (DL_FUNC) &_wishartinference_wishart_stats, 1},
    {"_wishartinference_lfafun_improper", (DL_FUNC) &_wishartinference_lfafun_improper, 5},
    {"_wishartinference_lfafun_proper", (DL_FUNC) &_wishartinference_lfafun_proper, 9},
    {"_wishartinference_mode_alphaEM", (DL_FUNC) &_wishartinference_mode_alphaEM, 12},
    {"_wishartinference_rejection_sampler", (DL_FUNC) &_wishartinference_rejection_sampler, 13},
    {"_wishartinference_wishart_inference", (DL_FUNC) &_wishartinference_wishart_inference, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_wishartinference(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
