# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello-world test to verify the library loaded correctly
#'
#' @return Always returns 0. Also prints "Hello from C++" as a side effect.
#' @export
test <- function() {
    .Call(`_wishartinference_test`)
}

#' Generate draws from a Wishart distribution
#'
#' Uses the Bartlett decomposition: if L is the lower Cholesky factor of
#' Sigma, then A = L * T satisfies W = A * A^T ~ Wishart_p(nu, Sigma),
#' where T is lower triangular with T(i,i) ~ sqrt(Chi^2(nu - i)) and
#' T(i,j) ~ N(0,1) for i > j.
#'
#' @param n Number of draws
#' @param p Dimension of the matrix, must be >= 2
#' @param nu Degrees of freedom, must be > p - 1
#' @param Sigma Scale matrix (p x p), must be positive definite
#' @return A cube of size (p, p, n) containing the Wishart draws
#' @export
rwishart <- function(n, p, nu, Sigma) {
    .Call(`_wishartinference_rwishart`, n, p, nu, Sigma)
}

#' Log of the multivariate Gamma function
#'
#' Defined as log Gamma_p(a) = p*(p-1)/4 * log(pi) plus the sum over
#' i = 1, ..., p of log Gamma(a - (i-1)/2). Required for the normalizing
#' constant of the Wishart and inverse-Wishart distributions.
#'
#' @param a Argument, must be > (p-1)/2
#' @param p Dimension
#' @return log Gamma_p(a)
#' @export
lgammap_export <- function(a, p) {
    .Call(`_wishartinference_lgammap_export`, a, p)
}

#' Log determinant of a positive definite matrix
#'
#' Uses Armadillo's log_det for numerical stability.
#'
#' @param X Square positive definite matrix
#' @return log|X|
#' @export
ldet <- function(X) {
    .Call(`_wishartinference_ldet`, X)
}

#' Compute sufficient statistics for Wishart observations
#'
#' Returns the sample mean matrix xbar and the log geometric mean of
#' determinants ldetxbarg, the sufficient statistics for (alpha, Sigma)
#' under X_i ~ Wishart_p(2*alpha, Sigma).
#'
#' @param X Cube of n Wishart draws, dimensions (p, p, n)
#' @return A list with \code{xbar} (p x p sample mean matrix) and
#'   \code{ldetxbarg} (log geometric mean of determinants)
#' @export
wishart_stats <- function(X) {
    .Call(`_wishartinference_wishart_stats`, X)
}

#' Log unnormalized marginal posterior of alpha under the improper prior
#'
#' The improper prior p(alpha,mu) propto (alpha-(p-1)/2)^(-1) *
#' |mu|^(-(p+1)/2), after marginalizing over mu, gives a closed-form
#' log posterior for alpha. Returns \code{-Inf} when \code{a <= (p-1)/2}.
#'
#' @param a Shape parameter alpha, must be > (p-1)/2
#' @param n Number of Wishart observations
#' @param p Dimension
#' @param xbar Sample mean matrix (p x p)
#' @param ldetxbarg Log geometric mean of determinants (1/n)*sum log|X_i|
#' @return log f*(alpha), or -Inf if alpha <= (p-1)/2
#' @export
lfafun_improper <- function(a, n, p, xbar, ldetxbarg) {
    .Call(`_wishartinference_lfafun_improper`, a, n, p, xbar, ldetxbarg)
}

#' Log unnormalized marginal posterior of alpha under the proper prior
#'
#' The proper prior alpha ~ Gamma(beta, beta*eta) (truncated at
#' (p-1)/2) and mu|alpha ~ inv-Wishart(2*kappa*alpha, 2*kappa*alpha*mu0),
#' after marginalizing over mu, gives a closed-form log posterior for
#' alpha. Returns \code{-Inf} outside the domain \code{alpha > (p-1)/2}.
#'
#' @param a Shape parameter alpha, must be > (p-1)/2
#' @param n Number of Wishart observations
#' @param p Dimension
#' @param ldet_muhat log|muhat| where muhat = (n*xbar + kappa*mu0)/(n+kappa)
#' @param ldetxbarg Log geometric mean of determinants (1/n)*sum log|X_i|
#' @param ldet_mu0 log|mu0|
#' @param beta Gamma prior shape, must be > 1
#' @param eta Gamma prior rate parameter
#' @param kappa inv-Wishart prior strength, must be >= 1
#' @return log f*(alpha), or -Inf if outside domain
#' @export
lfafun_proper <- function(a, n, p, ldet_muhat, ldetxbarg, ldet_mu0, beta, eta, kappa) {
    .Call(`_wishartinference_lfafun_proper`, a, n, p, ldet_muhat, ldetxbarg, ldet_mu0, beta, eta, kappa)
}

#' Find the posterior mode of alpha
#'
#' Dispatches to the improper- or proper-prior EM mode finder depending
#' on which parameters are supplied. The prior type is auto-detected:
#' omit \code{mu0}, \code{beta}, \code{eta}, \code{kappa} for the
#' improper prior; supply \code{mu0} and \code{beta > 1}, \code{kappa >= 1}
#' for the proper prior. Uses a Newton-within-EM algorithm.
#'
#' @param n Number of Wishart observations
#' @param p Dimension
#' @param xbar Sample mean matrix (p x p)
#' @param ldetxbarg Log geometric mean of determinants
#' @param mu0_ Prior center matrix (p x p); omit for improper prior
#' @param beta Gamma prior shape, must be > 1 (ignored if improper)
#' @param eta Gamma prior rate (ignored if improper)
#' @param kappa inv-Wishart prior strength, must be >= 1 (ignored if improper)
#' @param tol Convergence tolerance
#' @param prnt If TRUE, print EM iterates and bounds
#' @param max_em_iter Maximum number of EM iterations
#' @param max_nr_iter Maximum number of inner Newton-Raphson iterations
#' @return A numeric vector \code{c(ahat, log f*(ahat))}
#' @export
mode_alphaEM <- function(n, p, xbar, ldetxbarg, mu0_ = NULL, beta = 0.0, eta = 1.0, kappa = 0.0, tol = 1e-6, prnt = FALSE, max_em_iter = 1000L, max_nr_iter = 100L) {
    .Call(`_wishartinference_mode_alphaEM`, n, p, xbar, ldetxbarg, mu0_, beta, eta, kappa, tol, prnt, max_em_iter, max_nr_iter)
}

#' Rejection sampler for the joint posterior of (alpha, mu)
#'
#' Requires the posterior mode \code{ahat} and \code{mxlfa} = log f*(ahat)
#' from \code{mode_alphaEM()}, plus the covering Gamma parameters
#' \code{lambda} and \code{nu_star}. Prior type is auto-detected from
#' parameters, exactly as in \code{mode_alphaEM()}.
#'
#' @param ahat Posterior mode from \code{mode_alphaEM()[1]}
#' @param mxlfa log f*(ahat) from \code{mode_alphaEM()[2]}
#' @param lambda Covering Gamma rate
#' @param nu_star Covering Gamma shape (= ahat*lambda + 1)
#' @param p Dimension
#' @param n Number of Wishart observations
#' @param xbar Sample mean matrix (p x p)
#' @param ldetxbarg Log geometric mean of determinants
#' @param mu0_ Prior center matrix; omit for improper prior
#' @param beta Gamma prior shape; 0 = improper, must be > 1 if proper
#' @param eta Gamma prior rate; default 1.0
#' @param kappa inv-Wishart prior strength; 0 = improper, must be >= 1 if proper
#' @param nsamp Number of posterior samples (default 10000)
#' @return A list with \code{alpha_sample}, \code{mu_sample},
#'   \code{empirical_acpt_rate}, \code{theoretical_acpt_rate}
#' @export
rejection_sampler <- function(ahat, mxlfa, lambda, nu_star, p, n, xbar, ldetxbarg, mu0_ = NULL, beta = 0.0, eta = 1.0, kappa = 0.0, nsamp = 10000L) {
    .Call(`_wishartinference_rejection_sampler`, ahat, mxlfa, lambda, nu_star, p, n, xbar, ldetxbarg, mu0_, beta, eta, kappa, nsamp)
}

#' Bayesian inference for the Wishart shape parameter
#'
#' Given \code{X_1,...,X_n ~ iid Wishart_p(2*alpha, Sigma)}, computes the
#' posterior of (alpha, mu) where mu = alpha*Sigma, under either an
#' improper or proper prior. Runs the full pipeline: sufficient
#' statistics, EM mode finding, and rejection sampling.
#'
#' @param X Cube of n Wishart observations, dimensions (p, p, n)
#' @param mu0_ Prior center matrix (p x p); omit for improper prior
#' @param beta Gamma prior shape, must be > 1 (ignored if improper)
#' @param eta Gamma prior rate parameter (ignored if improper)
#' @param kappa inv-Wishart prior strength, must be >= 1 (ignored if improper)
#' @param nsamp Number of posterior samples
#' @param tol Convergence tolerance for the EM mode finder
#' @param prnt If TRUE, print EM iterates
#' @param max_em_iter Maximum number of EM iterations
#' @param max_nr_iter Maximum number of inner Newton-Raphson iterations
#' @return A list with \code{results} (alpha_samples, mu_samples, ahat,
#'   theoretical_acpt_rate, empirical_acpt_rate) and \code{statistics}
#'   (xbar, muhat, log_det_geometric_mean, cover_shape, cover_rate,
#'   elapsed_seconds). If a convergence failure is caught internally,
#'   returns \code{list(error = "...")} instead.
#' @export
wishart_inference <- function(X, mu0_ = NULL, beta = 0.0, eta = 1.0, kappa = 0.0, nsamp = 10000L, tol = 1e-6, prnt = FALSE, max_em_iter = 1000L, max_nr_iter = 100L) {
    .Call(`_wishartinference_wishart_inference`, X, mu0_, beta, eta, kappa, nsamp, tol, prnt, max_em_iter, max_nr_iter)
}

